export const GOOGLE_SIGN_IN = {
    INIT: "GOOGLE_SIGN_IN_INIT",
    SUCCESS: "GOOGLE_SIGN_IN_SUCCESS",
    ERROR: "GOOGLE_SIGN_IN_ERROR"
}

export const GOOGLE_SIGN_OUT = {
    INIT: "GOOGLE_SIGN_OUT_INIT",
    SUCCESS: "GOOGLE_SIGN_OUT_SUCCESS",
    ERROR: "GOOGLE_SIGN_OUT_ERROR"
}