export const FACEBOOK_SIGN_IN = {
    INIT: "FACEBOOK_SIGN_IN_INIT",
    SUCCESS: "FACEBOOK_SIGN_IN_SUCCESS",
    ERROR: "FACEBOOK_SIGN_IN_ERROR"
}

export const FACEBOOK_SIGN_OUT = {
    INIT: "FACEBOOK_SIGN_OUT_INIT",
    SUCCESS: "FACEBOOK_SIGN_OUT_SUCCESS",
    ERROR: "FACEBOOK_SIGN_OUT_ERROR"
}