export const USER_ACCOUNT_TYPE_GOOGLE = "USER_ACCOUNT_TYPE_GOOGLE";
export const USER_ACCOUNT_TYPE_GITHUB = "USER_ACCOUNT_TYPE_GITHUB";
export const USER_ACCOUNT_TYPE_FACEBOOK = "USER_ACCOUNT_TYPE_FACEBOOK";